a = input('Digite algo: ')
print('O tipo primitivo desse vsalor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('Só tem números?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Está em minúsculo?', a.islower())
print('Está capitalizada?', a.istitle())